(CMAKE ROSE) enable RTTI on Visual Studio
Pass the /GR compiler flag when building ROSE using Visual Studio.
This enables Run-Time Type Information.  Without this flag, ROSE
will throw an exception whenever an executable attempts to perform
a dynamic cast between ROSE classes.

Enabling this flag elicited a new compiler error:
  error C2593: 'operator <<' is ambiguous
  boost\exception\detail\is_output_streamable.hpp line 45

This error arose while compiling AstPerformance.C.  It was due to
the templated constructors for RangeMap & RangeMapVoid in rangemap.h.
The solution to this problem was to declare these two constructors as
explicit.

(cherry picked from commit (EDG3) f15b22b53f44b18e9406aed574a59869682ebce4)