(CMAKE ROSE) resolve C2668
This commit resolves a compilation error:
C2668: ambiguous call to overloaded function

This default constructor of CustomMemoryPoolDOTGeneration was unnecessary
due to the default argument of its other construtor.

(cherry picked from commit (EDG3) e534e99d00a0afd1671b0635a3e7531595b69a00)