(Empty) Retriggering Jenkins
/jenkins-edg4x/view/Integration/job/200-compile_with_rose-cherokee/96

Cloning repository rose-dev@rosecompiler.llnl.gov:rose/edg4x/rose-sh.git
git --version
git version 1.7.5
ERROR: Error cloning remote repo 'origin' : Could not clone rose-dev@rosecompiler.llnl.gov:rose/edg4x/rose-sh.git
hudson.plugins.git.GitException: Could not clone rose-dev@rosecompiler.llnl.gov:rose/edg4x/rose-sh.git
	at hudson.plugins.git.GitAPI.clone(GitAPI.java:271)
	at hudson.plugins.git.GitSCM$2.invoke(GitSCM.java:1040)
	at hudson.plugins.git.GitSCM$2.invoke(GitSCM.java:982)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2273)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: hudson.plugins.git.GitException: Command "git clone --progress -o origin rose-dev@rosecompiler.llnl.gov:rose/edg4x/rose-sh.git /export/tmp.hudson-rose/jenkins/edg4x/workspace/200-compile_with_rose-cherokee" returned status code 128: