(CMAKE ROSE) resolve C2036
This commit resolves the following compilation error:
error C2036: 'void *' : unknown size

This change still needs to be tested to ensure that it does not
modify the behavior of this code.

(cherry picked from commit (EDG3) ae4a285129390880c8166364cdfc42ca50d38027)