(Support) Backtraces disabled by default, not available on macOS
Backtraces take a long time to generate (a few seconds) and produce
lots of output, so we should have a way to conditionally
enable/disable them. The Rust ecosystem uses `RUST_BACKTRACE=1` and
prints a message when they're not shown, like this:

```
---- interval::tests::empty stdout ----
thread 'interval::tests::empty' panicked at ruselib/src/interval.rs:34:9:
assertion failed: false
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

ROSE should do something similar:

* backtrace: capability is compiled into the ROSE library where
  supported (non-macOS with boost >= 1.65).

* backtraces: are disabled at runtime by default and print a message
  about how to get a backtrace.

* backtraces: are enabled by setting `ROSE_BACKTRACE=1` (or anything
  but "0") in the environment.

Issue #452
Issue #453