Bugfix for 121339493:AstAttributeMechanism.h
GCC is confused since std::list has not been included
with #include <list> yet it seems to be handled by
Boost:

```bash
$ cmake ...
$ make ...
...
[ 89%] Building CXX object projects/extractMPISkeleton/src/CMakeFiles/extractMPISkeleton.dir/extractMPISkeleton.cc.o
In file included from rose/projects/extractMPISkeleton/src/APIDepAttrib.h:4,
                 from rose/projects/extractMPISkeleton/src/GenericDepAttrib.h:5,
                 from rose/projects/extractMPISkeleton/src/APISpec.h:7,
                 from rose/projects/extractMPISkeleton/src/APIReader.h:4,
                 from rose/projects/extractMPISkeleton/src/extractMPISkeleton.cc:4:
rose/src/midend/astProcessing/AstAttributeMechanism.h:254: error: wrong number of template arguments (1, should be 2)
/nfs/casc/overture/ROSE/opt/rhel6/x86_64/boost/1_45_0/gcc/4.4.5/include/boost/detail/container_fwd.hpp:81: error: provided for ‘template<class T, class Allocator> struct std::list’
make[2]: *** [projects/extractMPISkeleton/src/CMakeFiles/extractMPISkeleton.dir/extractMPISkeleton.cc.o] Error 1
make[1]: *** [projects/extractMPISkeleton/src/CMakeFiles/extractMPISkeleton.dir/all] Error 2
make: *** [all] Error 2
```